cat("Chapter 1: Basics p.4-6\n")
cat("Here is an ANOVA for the FishTank Data: A nested-factors design\n")
data<-read.table("../../data/FishTank.txt",sep = "",header=T)
print(head(data))
print(summary(data))
Diet<-as.character(data[,1])
Tank<-as.character(data[,2])
WtGain<-data[,3]
aovdata <- data.frame(WtGain,Diet,Tank)
cat("\n--------Nested ANOVA ---------------------\n")
cat("Model(WtGain ~ Diet + Tank)\n")
cat("----------This gives the full anova table, wrong tests----------------\n\n")
summary(aov(WtGain~Diet+Tank,data=aovdata))
cat("\nModel(WtGain ~ Diet + Error(Tank/Diet))\n")
cat("---------This gives the correct test on Diet with an error message-----------------------\n")
summary(aov(WtGain~Diet+Error(Tank/Diet),data=aovdata))
