cat("Chapter 1: Basics p.9-11\n")
cat("t-test for Strawberry data\n")
A<-c(10.1,10.8,9.8,10.5)
B<-c(6.3,6.9,5.3,6.2)
C<-c(8.4,9.4,9.0,9.2)

cat("Randomized Complete Block Designs")
cat("\n--------RCB ANOVA - A, B and C---------------------\n")
cat("--------Model(yield ~ block + trt)---------------\n\n")
yield<-c(A,B,C)
trt<-rep(c("A","B","C"),each=4)
block <- rep(c("1","2","3","4"),each=1,times=3)
strawdata <- data.frame(yield,block,trt)
print(strawdata)
summary(aov(yield ~ block + trt,strawdata))

cat("\n--------RCB ANOVA - Just A and B---------------------\n")
cat("--------Model(yield ~ block + trt)---------------\n")
t.test(A-B)
yield<-c(A,B)
trt<-rep(c("A","B"),each=4)
block <- rep(c("1","2","3","4"),each=1,times=2)
strawdata <- data.frame(yield,block,trt)
print(strawdata)
summary(aov(yield ~ block + trt,strawdata))

cat("\n--------RCB ANOVA - 0.5*A + 0.5*B - C---------------------\n")
cat("--------Model(yield ~ block + trt)---------------\n")
t.test(0.5*A+0.5*B-C)
yield<-c(0.5*A+0.5*B,C)
trt<-rep(c("0.5*A+0.5*B","C"),each=4)
block <- rep(c("1","2","3","4"),each=1,times=2)
strawdata <- data.frame(yield,block,trt)
print(strawdata)
summary(aov(yield ~ block + trt,strawdata))
